basePath: /api/v1/
definitions:
  responses.Analytic:
    properties:
      brightness:
        additionalProperties:
          type: integer
        type: object
    type: object
  responses.Error:
    properties:
      error:
        type: string
    type: object
  responses.Message:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: RESTful API endpoints for Image Conversion
  title: Image Converter API
  version: "1.0"
paths:
  /analytic:
    post:
      consumes:
      - multipart/form-data
      description: Analyse an image
      parameters:
      - description: Image file to analyse
        in: formData
        name: file
        required: true
        type: file
      produces:
      - image/png
      responses:
        "201":
          description: Conversion successful
          schema:
            $ref: '#/definitions/responses.Analytic'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Analyse an image
      tags:
      - Image
  /image/{back_color}/{fore_color}:
    post:
      consumes:
      - multipart/form-data
      description: Convert an image to a specified format
      parameters:
      - description: Image file to convert
        in: formData
        name: file
        required: true
        type: file
      - default: "000000"
        description: Background Color
        in: path
        name: back_color
        required: true
        type: string
      - default: FFFFFF
        description: Foreground Color
        in: path
        name: fore_color
        required: true
        type: string
      produces:
      - image/png
      responses:
        "201":
          description: Conversion successful
          schema:
            $ref: '#/definitions/responses.Message'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Convert an image
      tags:
      - Image
swagger: "2.0"
